project:
  type: website
  output-dir: docs

website:
  title: "Fonti Kar"
  navbar:
    search: true
    #   - presos.qmd
    #   - research.qmd
    #   - recipes.qmd

       

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: 
  mode: source

