project:
  type: website
  output-dir: docs

website:
  title: "Fonti Kar"
  navbar:
    search: true
    # left:
    #   - blog.qmd
    #   - presos.qmd
    #   - research.qmd
    #   - recipes.qmd
    # right: 
    #  - icon: github
    #    href: https://github.com/fontikar
    #  - icon: twitter
    #    href: https://twitter.com/fonti_kar
    #  - icon: mastodon
    #    href: https://fosstodon.org/@fontikar
       

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: 
  mode: source

