project:
  type: website
  output-dir: docs

website:
  title: "Fonti Kar"
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd
      - blog.qmd
      - presos.qmd
      - research.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: 
  mode: source

