---
title: "posit::conf(2024)"
draft: true
---

An inspiring community quote

I attend posit::conf(2024) as a Opportunity Scholar, if you are from a minority that is not well represented in the data science community, I highly recommend putting your name forward so you can experience posit::conf(2024). 

Why I wanted to go: I am at the point in my career where I want to venture out of the comfort zone of academia. I finished my PhD, I took on a job to work on my tool building and software carpentry skills, but I desperately miss answering questions. I wanted to see what are folks doing with their R/DS skills and see where I see myself? 

Expectation: To absorb and to learn and to be pretty invisible

Reality: To get really inspired

## Seeing people in the flesh, in 3D

Being an R programmer is an interesting experience. At least for me, I can say that I go to work, I turn on my computer and I code - by myself usually. If I need help, my first point of support is a search engine or a LLM which will usually point me to the resources that is developed by the R community.

This means that you start recognising names of resource creators or folks that are extremely helpful on forums like StackedOverflow or Posit Community. There is nothing more satisfying that finding a solution that helps you get unstuck. Usually the sense of gratitude stops there, unless you take the time out to message the author or reply in thread.

So at posit conf, to find myself putting names to faces, names that has helped me with very specific tasks, or names who I admire for their contributions in the R community through their tool building or resource creating, or public speaking - I was feeling overwhelmed initially, but when you start talking to these faces, I found a deep sense of gratitude. Talking to these faces, only reaffirmed that they are kind, giving and incredibly knowledgable and I felt a great sense of pride

That quote about standing on shoulders of giants, is so true here. 

Example: Stefanie and her community call magic, Steph Hazlit for her experience. Julie Lowndes leading science through openness. Or someone's hexsticker that means so much to you. Someone from Mastodon. Shannon on R-Ladies Global

## A small fry's impact

I was expecting to go to the conference to absorb, to learn, to be in the shadows and take it all in. 
I wasn't giving a talk, I wanted to see what could possibly do with my R and coding skills. 

Then you hear people say: "Oh my goodness, you're Fonti?!" was really surreal. I find it incredibly hard to take on positive feedback, I always push it off to the side, but these sort of interactions was hard to do that. 

To learn that the small things I've done to give back to the R DS community made someone's life easier made me feel reassured that I was doing something right...and I felt motivated to do more or continue being myself. 

## Shared love and pride 

My expectation for a big data science conference like posit::conf(2024) to be overwhelming and a bit siloed. That was from my experiences at large biology/evolution conferences. Everyone stuck with their labs and everyone had their own purpose and reasoning to attend certain talks. 

But what was a sharp contrast to my previous conference experiences is without saying very much, there is a shared love and pride for all the open source tools we are all so familar with.

It's much easier to get into conversations with new people, "What's your favourite package", "What kinda R do you do?" "Coolest hex or talk you've seen so far?". 

The general sense of the talks I attended were not focussed on "Check out this amazing thing I did" but a softer "Hey I did this cool thing in my free time, and I encourage you to do the same because its amazing to do great things together". The latter is from established tools like Joe Cheng at his Shiny AI talk, but also from newer tools like Quarto and scrollytelling through to, how I got my team to do cool things. 

I don't know how to articulate WHY that is the case but you can just "feel the buzz" and that buzz is so damn infectious and it DOES make you want to go home to your computer and try out all the new things you learned. 

## Final take homes

My experience of the R Data Science Community is warm and fuzzy, inside and out. 
People are so generous and kind with their time and skills in sharing their knowledge with everyone.
Your contributions, no matter how small or insignificant you think it may be, can still drive positivity. 

Perhaps there is something in the water with open source spaces, the shared need, the shared enthusiam, the shared altrusiam, but the R and posit DS community really champions the quote "sharing is caring". 







